---
- hosts: "am-local"

  pre_tasks:

    - include_vars: "vars-singlenode.yml"
      tags:
        - "always"
    - name: "Install packages for development convenience"
      apt:
        pkg: "{{ item }}"
        state: "latest"
      with_items:
        - "fish"
      sudo: "yes"

  roles:

    - role: "elasticsearch"
      sudo: "yes"
      tags:
        - "elasticsearch"

    - role: "percona"
      sudo: "yes"
      tags:
        - "percona"

    - role: "gearman"
      sudo: "yes"
      tags:
        - "gearman"

    - role: "nginx"
      sudo: "yes"
      tags:
        - "nginx"

    - role: "archivematica-src"
      sudo: "yes"
      tags:
        - "archivematica-src"
